server:
  port: 8188
spring:
  application:
    name: jpademo
  datasource:
    url: jdbc:mysql://172.23.20.101:5688/yearning?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useServerPrepStmts=true&cachePrepStmts=true
    username: root
    password: root123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: true
