server:
  port: 8003
  compression:
    enabled: true
  http2:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

spring:
  application:
    name: kele-service-gateway
  cloud:

    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: kele-service-provider
          uri: lb://kele-service-provider
          predicates:
            - Path=/provider/**
          filters:
            - RewritePath=/provider(?<segment>/?.*), $\{segment}

        - id: kele-service-comsummer
          uri: lb://kele-service-comsummer
          predicates:
            - Path=/comsummer/**
          filters:
            - RewritePath=/comsummer(?<segment>/?.*), $\{segment}

        - id: kele-service-resource-server
          uri: lb://kele-service-resource-server
          predicates:
            - Path=/resource/**
          filters:
            - RewritePath=/resource(?<segment>/?.*), $\{segment}

        #转发websocket 请求
        - id: kele-websocket-server
          uri: lb:ws://kele-websocket-server
          predicates:
            - Path=/ws/**
          filters:
            - RewritePath=/ws(?<segment>/?.*), $\{segment}
        - id: kele-websocket-broker
          uri: lb:ws://kele-websocket-broker
          predicates:
            - Path=/wsbroker/**
          filters:
            - RewritePath=/wsbroker(?<segment>/?.*), $\{segment}
