server:
  port: 8010

spring:
  application:
    name: kele-websocket-server
  redis:
    host: 172.23.20.101
    database: 4
    password: 0192023a7bbd73250516f069df18b500
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
