server:
  port: 8002

spring:
  application:
    name: kele-service-comsummer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    com:
      kele:
        aggregation:
          rpc: debug


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
